name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Build HTML in temporary folder
      - run: |
          sphinx-build -b html docs/ docs/_build/html html_baseurl="https://kwat0308.github.io/smiet-docs/"

      # 6. Commit and push changes
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: main          # deploy into /docs on main
          destination_dir: docs         # push into this folder
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          keep_files: false             # remove old files before pushing
